name: RijksMuseum
options:
  bundleIdPrefix: com.tavares
packages:
  SFSafeSymbols:
    url: https://github.com/piknotech/SFSafeSymbols.git
    from: 1.0.0
  Logging:
    url: "https://github.com/apple/swift-log.git"
    from: 1.0.0
targets:
  RijksMuseum:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    sources: Sources/RijksMuseum
    dependencies:
      - package: SFSafeSymbols
      - package: Logging
    scheme:
      testTargets:
        - RijksMuseumTests
  RijksMuseumTests:
    type: bundle.unit-test
    platform: iOS
    sources: Tests/RijksMuseumTests
    dependencies:
      - target: RijksMuseum
    scheme:
      testTargets:
        - RijksMuseumTests
